name: flutter_mock_web_server
description: flutter_mock_web_server is a null-safe package allowing for easy mocking tests for Dart and Flutter development, targeting developers who need to test their HTTP clients without relying on external sources.
version: 1.0.1
homepage: https://github.com/jandrop/flutter_mock_web_server

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  http: ^1.6.0
  stack_trace: ^1.12.1

dev_dependencies:
  test: ^1.26.3