name: flutter_mock_web_server
description: flutter_mock_web_server is a null-safe package allowing for easy mocking tests for Dart and Flutter development, targeting developers who need to test their HTTP clients without relying on external sources.
version: 1.0.0
homepage: https://github.com/jandrop/flutter_mock_web_server

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  http: ^0.13.5
  stack_trace: ^1.10.0

dev_dependencies:
  test: ^1.17.11


